### Авторизация
POST http://zolotomania.loc/fivecms/json/1c_exchange.php?type=catalog&mode=check_auth
Cache-Control: no-cache
Authorization: Basic YWRtaW46djRpNmsxaWc5
###

### Загрузка файлоа
POST http://zolotomania.loc/fivecms/json/1c_exchange.php?type=catalog&mode=file&filename=v8_837_2df7b.zip
Cache-Control: no-cache
Authorization: Basic YWRtaW46djRpNmsxaWc5
Cookie: XDEBUG_SESSION=1; PHPSESSID=52onmc7rptq70dme5r49flf7duv3vdoo;

< E:/OpenServer/domains/zolotomania.loc/_temp/v8_837_2df7b.zip
###

### Распаковка архива из папки temp
POST http://zolotomania.loc/fivecms/json/1c_exchange.php?type=catalog&mode=file&unpacking=true&filename=full_v8_DC95_833a.zip
Cache-Control: no-cache
Authorization: Basic YWRtaW46djRpNmsxaWc5
Cookie: XDEBUG_SESSION=1; PHPSESSID=52onmc7rptq70dme5r49flf7duv3vdoo;
###

### Импорт категорий
POST http://zolotomania.loc/fivecms/json/1c_exchange.php?type=catalog&mode=import_categories&update=false
Cache-Control: no-cache
Authorization: Basic YWRtaW46djRpNmsxaWc5
Cookie: XDEBUG_SESSION=1; PHPSESSID=52onmc7rptq70dme5r49flf7duv3vdoo;
###ё

### Импорт товаров
POST http://zolotomania.loc/fivecms/json/1c_exchange.php?type=catalog&mode=import_products&filename=import_products.json&update=false
Cache-Control: no-cache
Authorization: Basic YWRtaW46djRpNmsxaWc5
Cookie: XDEBUG_SESSION=1; PHPSESSID=52onmc7rptq70dme5r49flf7duv3vdoo;
###

### Импорт вариантов
POST http://zolotomania.loc/fivecms/json/1c_exchange.php?type=catalog&mode=import_variants&filename=import_variants.json&update=false
Cache-Control: no-cache
Authorization: Basic YWRtaW46djRpNmsxaWc5
Cookie: XDEBUG_SESSION=1; PHPSESSID=52onmc7rptq70dme5r49flf7duv3vdoo;
###


### Импорт пользователей
POST http://zolotomania.loc/fivecms/json/1c_exchange.php?type=users&mode=import&filename=import_users.json
Cache-Control: no-cache
Authorization: Basic YWRtaW46djRpNmsxaWc5
Cookie: XDEBUG_SESSION=1; PHPSESSID=52onmc7rptq70dme5r49flf7duv3vdoo;
###


### Экспорт ордеров
POST http://zolotomania.loc/fivecms/json/1c_exchange.php?type=sales&mode=export&date_begin=2020-01-01&date_end=2020-10-09&status=0
Cache-Control: no-cache
Authorization: Basic YWRtaW46djRpNmsxaWc5
Cookie: XDEBUG_SESSION=1; PHPSESSID=52onmc7rptq70dme5r49flf7duv3vdoo;
###

### Импорт ордеров
POST http://zolotomania.loc/fivecms/json/1c_exchange.php?type=sales&mode=import&filename=import_orders.json
Cache-Control: no-cache
Authorization: Basic YWRtaW46djRpNmsxaWc5
Cookie: XDEBUG_SESSION=1; PHPSESSID=52onmc7rptq70dme5r49flf7duv3vdoo;
###
