### Авторизация
POST https://xn----8sbtgmhidba7b6k.xn--p1ai/fivecms/json/1c_exchange.php?type=catalog&mode=check_auth
Cache-Control: no-cache
Authorization: Basic YWRtaW46djRpNmsxaWc5
###

### Загрузка файлоа
POST https://xn----8sbtgmhidba7b6k.xn--p1ai/fivecms/json/1c_exchange.php?type=catalog&mode=file&filename=v8_837_2df7b.zip
Cache-Control: no-cache
Authorization: Basic YWRtaW46djRpNmsxaWc5
Cookie: PHPSESSID=a995dd276d12a528733977e5fc9603c2;

< E:/OpenServer/domains/zolotoy-telets.loc/_temp/v8_837_2df7b.zip
###

### Распаковка архива из папки temp
POST https://xn----8sbtgmhidba7b6k.xn--p1ai/fivecms/json/1c_exchange.php?type=catalog&mode=file&unpacking=true&filename=v8_837_2df7b.zip
Cache-Control: no-cache
Authorization: Basic YWRtaW46djRpNmsxaWc5
Cookie: PHPSESSID=a995dd276d12a528733977e5fc9603c2;
###

### Импорт категорий
POST https://xn----8sbtgmhidba7b6k.xn--p1ai/fivecms/json/1c_exchange.php?type=catalog&mode=import_categories&update=false
Cache-Control: no-cache
Authorization: Basic YWRtaW46djRpNmsxaWc5
Cookie: PHPSESSID=a995dd276d12a528733977e5fc9603c2;
###

### Импорт товаров
POST https://xn----8sbtgmhidba7b6k.xn--p1ai/fivecms/json/1c_exchange.php?type=catalog&mode=import_products&filename=import_products.json&update=false
Cache-Control: no-cache
Authorization: Basic YWRtaW46djRpNmsxaWc5
Cookie: PHPSESSID=a995dd276d12a528733977e5fc9603c2;
###

### Импорт вариантов
POST https://xn----8sbtgmhidba7b6k.xn--p1ai/fivecms/json/1c_exchange.php?type=catalog&mode=import_variants&filename=import_variants.json&update=false
Cache-Control: no-cache
Authorization: Basic YWRtaW46djRpNmsxaWc5
Cookie: PHPSESSID=a995dd276d12a528733977e5fc9603c2;
###


### Импорт пользователей
POST https://xn----8sbtgmhidba7b6k.xn--p1ai/fivecms/json/1c_exchange.php?type=users&mode=import&filename=import_users.json
Cache-Control: no-cache
Authorization: Basic YWRtaW46djRpNmsxaWc5
Cookie: PHPSESSID=a995dd276d12a528733977e5fc9603c2;
###


### Экспорт ордеров
POST https://xn----8sbtgmhidba7b6k.xn--p1ai/fivecms/json/1c_exchange.php?type=sales&mode=export&date_begin=2021-01-01 00:00:00&date_end=2021-01-12 11:00:00&status=1
Cache-Control: no-cache
Authorization: Basic YWRtaW46djRpNmsxaWc5
Cookie: PHPSESSID=a995dd276d12a528733977e5fc9603c2;
###
